services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\Imager\:
    resource: '../Classes/*'

  In2code\Imager\Controller\ImageController:
    public: true

  In2code\Imager\Domain\Repository\LlmRepository:
    public: true
